#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
echo "Clone Toolchains"
git clone -j32 https://github.com/najahiiii/aarch64-linux-gnu.git -b 4.9-mirror gcc
echo "Done"
echo "Clone AnyKernel"
git clone -j32 https://github.com/TaufiqRolex/AnyKernel.git -b life AnyKernel
echo "Done"
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
export ARCH=arm64
export KBUILD_BUILD_USER=A.Dev
export KBUILD_BUILD_HOST=LifeBox
# Compile plox
function compile() {
        make -s -C $(pwd) O=out daisy_defconfig
        make -C $(pwd) CROSS_COMPILE=${GCC} O=out -j32 -l32 2>&1| tee build.log
            if ! [ -a $IMAGE ]; then
                exit 1
            fi
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
}
# Zipping
function zipping() {
        cd AnyKernel
        zip -r9 Re-LifeKernel-Pie-${tanggal}.zip *
        cd ..
}
compile
zipping
